environment:
  HOME: $(HOMEDRIVE)$(HOMEPATH)

cache:
  - $(HOME)\.gradle\caches\build-cache-1
  - $(HOME)\.gradle\caches\jars-1
  - $(HOME)\.gradle\caches\jars-2
  - $(HOME)\.gradle\caches\jars-3
  - $(HOME)\.gradle\caches\modules-2
  - $(HOME)\.gradle\caches\transforms-1
  - $(HOME)\.gradle\wrapper\dists
  - $(HOME)\.m2\repository

configuration:
  - jdk1.8.0
  - jdk9
  - jdk10
  - jdk11

install:
  - if not exist %HOME%\.gradle mkdir %HOME%\.gradle
  - echo org.gradle.java.home=C:/Program Files/Java/%CONFIGURATION% > %HOME%\.gradle\gradle.properties
  - gradlew -v

build_script:
  - gradlew clean build

on_finish:
  - gradlew --stop # Fix "fileHashes.bin" being used by another process.
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $pattern = '**\build\test-results\**\TEST-*.xml'
      foreach ($file in (Resolve-Path $pattern)) {
        (New-Object 'System.Net.WebClient').UploadFile($url, $file)
      }