rootProject.name = "valiktor"

include("valiktor-core")
include("valiktor-javamoney")
include("valiktor-javatime")
include("valiktor-jodamoney")
include("valiktor-jodatime")
include("valiktor-spring:valiktor-spring")
include("valiktor-spring:valiktor-spring-boot-autoconfigure")
include("valiktor-spring:valiktor-spring-boot-starter")
include("valiktor-test")
include("valiktor-samples:valiktor-sample-collections")
include("valiktor-samples:valiktor-sample-custom-constraint")
include("valiktor-samples:valiktor-sample-custom-formatter")
include("valiktor-samples:valiktor-sample-hello-world")
include("valiktor-samples:valiktor-sample-javamoney")
include("valiktor-samples:valiktor-sample-javatime")
include("valiktor-samples:valiktor-sample-jodamoney")
include("valiktor-samples:valiktor-sample-jodatime")
include("valiktor-samples:valiktor-sample-nested-properties")
include("valiktor-samples:valiktor-sample-spring-boot-1-webmvc")
include("valiktor-samples:valiktor-sample-spring-boot-2-webmvc")
include("valiktor-samples:valiktor-sample-spring-boot-2-webflux-controller")
include("valiktor-samples:valiktor-sample-spring-boot-2-webflux-functional")